#!/usr/bin/env bash                                                           
# Install and configure HAproxy on your lb-01 server                          
sudo apt-get update
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.6(LTS)
sudo apt-get update
sudo apt-get -y install haproxy=2.6(LTS).\*
options="\n\tbind :80\n\tmode http\n\tuse_backend mybackend\nbackend mybackend\n\tbalance roundrobin\n\tserver [STUDENT_ID]-web-01 52.23.178.190 check\n\tserver [STUDENT_ID]-web-02 54.87.217.69 check"
sed -i '/errorfile 504/a frontend myconf' /etc/haproxy/haproxy.cfg
sed -i "s/frontend myconf/&$options/g" /etc/haproxy/haproxy.cfg
sudo service haproxy restart
